### ISSUE TITLE
User is never signed in

### ISSUE THREAD

**Issue by Frankofoedu** [amoraitis/TodoList#25] opened 2019-09-04 09:14 UTC
**Describe the bug**
var currentUser = await _userManager.GetUserAsync(User);  returns null on sign in

**To Reproduce**
1. Login or sign up new account
2. Page redirects to Home page without signing

**Expected behavior**
User should be signed in.

**Comment by amoraitis** [comment] 2019-09-04 14:54
@Frankofoedu Thanks, for reporting this bug. 

I was able to sign in and signup(Ensure that your development environment is ready to run the app). It seems that there is an exception at `EmailSender` service because there is no SendGrid API key to use. Although, you can still sign in with the user you created with the registration form.

#### Solution

We should update the module to bypass this in a development environment. 

- First, we should check if a SendGrid API key is set in the configuration.

- If it's set go ahead and send the email.

- If not, log an error, and exit the method(Don't try to send an email at all).

Let me know if you are able to work on this, or if you want further clarification.
This moved to a new issue #26

**Comment by Frankofoedu** [comment] 2019-09-04 15:08
I guess i want clear with my initial report. I signed up normally and received the email. When i clicked the link, i was redirected to localhost. The bug occurs when i close my dev environment and restart the app. The sign in process works as you can see below
![TodoList (Debugging) - Microsoft Visual Studio 9_4_2019 4_01_43 PM](https://user-images.githubusercontent.com/20884394/64267270-06245380-cf2e-11e9-8e05-8b3ca8a46728.png)

 but when it goes to the home controller and checks for signed in user, it returns null
![TodoList (Debugging) - Microsoft Visual Studio 9_4_2019 4_02_04 PM - Copy](https://user-images.githubusercontent.com/20884394/64267352-248a4f00-cf2e-11e9-8874-2a851ea7a257.png)


. I attached screenshots. If you need more explanation, i would be glad to help

**Comment by amoraitis** [comment] 2019-09-04 15:21
@Frankofoedu  I wasn't able to reproduce this bug. Could you please tell me which environment are you running in?
development, production or IIS?
Run it in Development environment and tell me if you get any (database) error in the console, while you are registering the user
Also, make sure that you are using the right credentials(Just in case).

**Comment by Frankofoedu** [comment] 2019-09-04 16:53
I changed the project setting to run on iis but i havent been able to get it to start. It keeps saying 'unable to connect to web server IIS Express'. 

I close the solutiion , then delete the .vs folder, change the ports in the appsettings.json file and reopen the solution.


```
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:63543",
      "sslPort": 3456
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "http://localhost:63543",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Developement"
      }
    },
    "TodoList.Web": {
      "commandName": "Project",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "http://localhost:63543/"
    },
    "TodoList.Web(Production)": {
      "commandName": "Project",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Production"
      },
      "applicationUrl": "http://localhost:63543/"
    }
  }
}
```



I get a new error message 
System.IO.FileNotFoundException: 'The configuration file 'appsettings.Developement.json' was not found and is not optional. The physical path is 'C:\Users\Frank\Source\Repos\TodoList\TodoList.Web\appsettings.Developement.json'.'

**Comment by Frankofoedu** [comment] 2019-09-04 17:00
To bypass the filenotfounderror, i had to comment out a line in the startup.cs constructor

```
 public Startup(IHostingEnvironment environment)
        {
            Configuration = new ConfigurationBuilder()
            .SetBasePath(environment.ContentRootPath)
            .AddJsonFile("appsettings.json", false, true)
           // .AddJsonFile($"appsettings.{environment.EnvironmentName}.json")
            .AddEnvironmentVariables()
            .AddUserSecrets<Startup>()
            .Build();
            Environment = environment;
        }
```

This now finally runs the project but without the css and js files

**Comment by amoraitis** [comment] 2019-09-04 19:40
> To bypass the filenotfounderror, i had to comment out a line in the startup.cs constructor
> 
> ```
>  public Startup(IHostingEnvironment environment)
>         {
>             Configuration = new ConfigurationBuilder()
>             .SetBasePath(environment.ContentRootPath)
>             .AddJsonFile("appsettings.json", false, true)
>            // .AddJsonFile($"appsettings.{environment.EnvironmentName}.json")
>             .AddEnvironmentVariables()
>             .AddUserSecrets<Startup>()
>             .Build();
>             Environment = environment;
>         }
> ```
> 
> This now finally runs the project but without the css and js files

Why should you have to change all of these, in order to run it? It's easy to run the app, you don't need to choose IIS if you haven't installed it on your machine. Kestrel will run your app. You just click run, right after you cloned it.

Also, how running on IIS will help you find out why the user is not found? Please explain me why do you have to do all of these? I m closing this, because its off topic. If you cannot setup the project, just contact me at twitter: amoraitis_me or email: anas.moraitis@gmail.com

**Closed as completed by amoraitis** 2019-09-04 19:40 UTC
Labels: bug
